apiVersion: batch/v1
kind: Job
metadata:
  generateName: ml-job-different-db-
spec:
  template:
    metadata:
      labels:
        app: ml-container
    spec:
      containers:
        - name: ml-container
          image: docker.io/gabriellimab522/rules_gen:1.0
          env:
            - name: DB_PATH
              value: /app/dataset/2023_spotify_ds2.csv
          volumeMounts:
          - mountPath: /app/shared_volume
            name: shared-volume
          - mountPath: /app/dataset
            name: dataset-volume
      restartPolicy: Never
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: project2-pvc-gabrielbarros
      - name: dataset-volume
        hostPath:
          path: /home/gabrielbarros/tp2_cloud/datasets
          type: Directory
  backoffLimit: 1
      