apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: gabrielbarros
  name: project2-pv2-gabrielbarros
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: default-storage-class
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /home/gabrielbarros/project2-pv2