apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc-gabrielbarros
  namespace: gabrielbarros
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local